### ISSUE TITLE
winston waveserver

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#50]
Has anyone else had this error when accessing data from a Winston inside a parfor loop? The same error isn't generated if I run the same code serially (for loop).
I've had success using this method in the past, so not sure where the problem lies.

I'm running CentOS 6.3, Java version 1.7.0_25, and MATLAB R2015b. 

Error using load_winston>getFromWinston (line 81)
Error using load_winston>getFromWinston (line 81)
Java exception occurred:
java.lang.ArrayIndexOutOfBoundsException: 93031
    at gov.usgs.earthworm.TraceBuf.traceBufToWave(TraceBuf.java:355)
    at gov.usgs.earthworm.WaveServer.getRawData(WaveServer.java:227)

Error in load_winston (line 44)
    [w, status] = getFromWinston(scnl,t1,t2,myDataSource);

Error in waveform (line 137)
            w = myLoadRoutine( makeDataRequest(ds,scnls,startt,endt) );

Thanks,
John

**Comment by gthompson** [comment]
Thanks for reporting this. From the stack trace, the exception is being thrown inside the Earthworm/Java WaveServer client (gov.usgs.earthworm.TraceBuf.traceBufToWave), not in GISMO/MATLAB code directly.

Because it only appears when Winston requests are made inside a parfor loop, this looks like a concurrency / thread-safety problem in the underlying Java client and/or Winston/WaveServer responses under simultaneous requests. In practice we’ve found the safest approach is to avoid parallel Winston reads and instead:
	•	fetch data serially (plain for), or
	•	fetch per worker using separate connections/sessions (if you control the codepath), or
	•	download/copy the data locally (MiniSEED/SDS) and parallelise processing rather than network IO.

Given the age of the reported stack (CentOS 6 / Java 7 / MATLAB R2015b) and that the failure appears upstream of GISMO, we don’t have a reproducible GISMO-side fix to apply here. I’m going to close this as an upstream dependency / environment issue, but please reopen if you can provide a minimal reproducible example on a current MATLAB + Java stack, or if you can confirm the problem persists with a newer Earthworm/WaveServer client.
